### ISSUE TITLE
参数如何填写的请教

### ISSUE THREAD

**Issue by TangledHusky** [2621532542/iOS_NQConfuseTool#1]
![image](https://user-images.githubusercontent.com/11520216/71792180-a7551f00-3072-11ea-810d-5d43033c38b0.png)

你好，我不知道这里如何填写，如果我想整个项目混淆，这里必须填写吗，我尝试填写了几个，但不起作用，请问下我该如何处理呢？

**Comment by 2621532542** [comment]
那是要修改成员属名的，填前缀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TangledHusky <notifications@github.com&gt;
发送时间: 2020年1月6日 10:54
收件人: 2621532542/iOS_NQConfuseTool <iOS_NQConfuseTool@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[2621532542/iOS_NQConfuseTool] 参数如何填写的请教 (#1)





 
你好，我不知道这里如何填写，如果我想整个项目混淆，这里必须填写吗，我尝试填写了几个，但不起作用，请问下我该如何处理呢？
