### ISSUE TITLE
一点开始就无响应了

### ISSUE THREAD

**Issue by happy201993** [2621532542/iOS_NQConfuseTool#3]

**Comment by 2621532542** [comment]
是下载安装的最新的吗

**Comment by happy201993** [comment]
是的 iOS_NQConfuseTool 2020-02-01 19-46-16.dmg

**Comment by 2621532542** [comment]
明天我看看

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: happy201993 <notifications@github.com&gt;
发送时间: 2020年2月19日 10:09
收件人: 2621532542/iOS_NQConfuseTool <iOS_NQConfuseTool@noreply.github.com&gt;
抄送: 2621532542 <2621532542@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[2621532542/iOS_NQConfuseTool] 一点开始就无响应了 (#3)




是的 iOS_NQConfuseTool 2020-02-01 19-46-16.dmg

**Comment by 2621532542** [comment]
其它人有这个问题没，有的话留言一下， 我刚看了下， 没出现问题，如果有，mac版本更新一下试试

**Comment by lcddhr** [comment]
@2621532542 有源码么，只选择了修改类名，swift 项目, 也是卡住了

**Comment by 2621532542** [comment]
> @2621532542 有源码么，只选择了修改类名，swift 项目, 也是卡住了

项目能删除敏感内容后， 发份我，方便查找一下是哪里的问题吗？

**Comment by mcu1993** [comment]
一样卡住，无响应

**Comment by 2621532542** [comment]
重要提示:之前点开始卡顿, 建议先将pod文件删除, 混淆之后,再pod install.
